name: inbound-reclamation-service
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdatabi:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: posts
      TZ: "Europe/Sofia"
      PGTZ: "Europe/Sofia"

volumes:
  pgdatabi: